#ifndef STRUCTS
#define STRUCTS

enum class Round
{
    SEEDING,
    ELIMINATION,
    NONE,
};

enum class SeedingRoundState
{
    TURNING_TOWARDS_START_CORNER_FROM_START,
    MOVING_TOWARDS_START_CORNER_FROM_START,
    TURNING_TOWARDS_BUTTON_CORNER_FROM_START,
    MOVING_TOWARDS_BUTTON_CORNER_FROM_START_CORNER,
    TURNING_TOWARDS_CENTER_FROM_BUTTON_CORNER,
    MOVING_TOWARDS_CENTER_FROM_BUTTON_CORNER,
    TURNING_TOWARDS_BUTTON_FROM_CENTER,
    MOVING_TOWARDS_BUTTON_FROM_CENTER,
    MOVING_TOWARDS_CENTER_FROM_BUTTON,
    TURNING_TOWARDS_BUTTON_CORNER_FROM_CENTER,
    MOVING_TOWARDS_BUTTON_CORNER_FROM_CENTER,
    TURNING_TOWARDS_START_CORNER_FROM_BUTTON_CORNER,
    MOVING_TOWARDS_START_CORNER_FROM_BUTTON_CORNER,
    STOPPED,
};

enum class EliminationRoundState
{
    POWER_ON,
    MOVING_BACKWARDS_FROM_STATION,
    TURNING_AWAY_FROM_WALL,
    MOVING_AWAY_FROM_OBSTACLES,
    MOVING_TOWARDS_NEXT_STATION,
    TURNING_TOWARDS_PERPENDICULAR_BUTTON_WALL,
    MOVING_TOWARDS_PERPENDICULAR_BUTTON_WALL,
    MOVING_AWAY_FROM_PERPENDICULAR_BUTTON_WALL,
    TURNING_TOWARDS_CHARGER_FROM_CORNER,
    MOVING_TOWARDS_CHARGER_FROM_CORNER,
    CHARGING,
    STOPPED,
};

#endif
